# Generated by Django 3.1.4 on 2020-12-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Branch_code',
            new_name='Branch_Code',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='brach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Qt.branch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Qt.item'),
        ),
    ]
