# Generated by Django 3.1.4 on 2020-12-10 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Qt', '0002_auto_20201210_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Transaction_Type',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
