# Generated by Django 3.1.4 on 2020-12-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qt', '0002_auto_20201210_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='brach',
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Qt.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Branch_Code',
            field=models.CharField(max_length=300),
        ),
    ]
