# Generated by Django 3.1.4 on 2020-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qt', '0004_auto_20201210_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branch_Code',
            field=models.CharField(max_length=300),
        ),
    ]
